# Generated by Django 5.2.1 on 2026-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbmovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('release_date', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.BigIntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('original_language', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DBMovies',
                'managed': False,
            },
        ),
    ]
